#!/bin/bash

function Help {
    echo "Usage:"
    echo "--entry"
    echo "    Create a desktop shortcut for operating this enlistment. This should be done in --enlist."
    echo "--enlist"
    echo "    Enlist all repos in the current directory."
    echo "--fix"
    echo "    Enlist repos that does not exist in the current directory."
}

function GitClone {
    git clone git@github.com:vczh-libraries/${1}.git
}

function Entry {
    for i in `seq 1 101`; do
        if [ "$i" == "101" ]; then
            echo "You have too many enlistments!"
            exit 1
        fi
        local VFILE=${VCPWD}/vle_${i}.desktop
        if ! [ -a ${VFILE} ]; then
            echo "Creating ${VFILE} ..."
            break
        fi
    done

    local VNAME_USER=""
    local VNAME="Enlistment (${PWD})"
    echo "Enter the display name (${VNAME}):"
    read VNAME_USER
    if ! [ "${VNAME_USER}" == "" ]; then
        VNAME=${VNAME_USER}
    fi
    local VPATH=${PWD}

    local VPATTERNS="s?<NAME>?${VNAME}?g;"$'\n'"s?<PATH>?${VPATH}?g;"$'\n'"s?<VCPROOT>?${VCPROOT}?g;"$'\n'"s?<VCPWD>?${VCPWD}?g;"

    sed -e "${VPATTERNS}" "${VCPROOT}/vl/vle-template.desktop" > "${VFILE}"
    chmod u+x "${VFILE}"

    sed -e "${VPATTERNS}" "${VCPROOT}/vl/vle-template.sh" > "${VPATH}/load.sh"
    chmod u+x "${VPATH}/load.sh"
}

GITHUB_REPOS=(Tools Vlpp Workflow GacUI GacJS Release XGac iGac Document vczh-libraries.github.io)

function Enlist {
    if [ ${PWD}/Tools/Ubuntu/vl/.. == ${VCPROOT} ]; then
        echo "Repos cannot be enlisted in the folder for *.desktop files."
        exit 1
    fi
    for i in "${GITHUB_REPOS[@]}"; do
        GitClone $i
    done
    Entry
}

function Fix {
    if ! [ -a load.sh ]; then
        echo "If you want to create a new enlistment, use --enlist."
        exit 1
    fi
    for i in "${GITHUB_REPOS[@]}"; do
        if ! [ -d "$i" ]; then
            GitClone $i
        fi
    done
}

case $1 in
    --help)
    Help
    ;;

    --entry)
    Entry
    ;;

    --enlist)
    Enlist
    ;;

    --fix)
    Fix
    ;;

    *)
    echo "Use --help for more information."
    ;;
esac
