#!/bin/bash

echo "vhelp"
echo "    Help information for Vczh Libraries Control Panel."
echo "vssh --help"
echo "    Quick way to setup ssh key for your github account."
echo "vapt --help"
echo "    Download necessary softwares."
echo "vsync --help"
echo "    Enlist all repos from github."
